### ISSUE TITLE
Errors in the submission of tasks

### ISSUE THREAD

**Issue by mxsph** [thm-mni-ii/feedbacksystem#432]
There are a number of errors in the submission of tasks:

- [x] If a text (Type Text) was submitted, the request fails with a 404 error:
![grafik](https://user-images.githubusercontent.com/63304184/96167590-ed9fae80-0f1f-11eb-83a6-cded927f0ad3.png)
- [x] If something is submitted, the result is requested too early, so the new results are not displayed
- [x] The Checker configuration does not have a return button.

**Comment by andrej-sajenko** [comment]
First bug should be solved by 9db08bd41124014872281faf92365af84e26668a Hab to create a blob with the text as content before uploading it.

**Comment by andrej-sajenko** [comment]
Have added a return button to address your third point---see 9787a6192124c70590aab85643c3b2aa5e79adf9

**Comment by andrej-sajenko** [comment]
We could delay the request of the results. But would it solve the problem? If so, what should be the appropriate delay time?

**Comment by mxsph** [comment]
> 
> 
> We could delay the request of the results. But would it solve the problem? If so, what should be the appropriate delay time?

yes, that probably does not solve the problem either. The best solution would be if the server can tell the client that the results are there.

**Comment by andrej-sajenko** [comment]
I think it should be okay, if we poll the results from time to time or if the user is required to update the page.
